version: '3'
services:
  worksync:
    build: .
    ports:
      - "3000:3000"  # Expose frontend port
      - "1000:1000"  # Expose backend port
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=2048  # Limit Node.js memory to 512MB
    volumes:
      - .:/app  # Mount the current directory
    networks:
      - worksync-network
    deploy:
      resources:
        limits:
          memory: 512M
    command: ["sh", "-c", "node /app/backend/app.js & npm start --prefix /app/frontend"]

networks:
  worksync-network:
    driver: bridge
