version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - worksync-network
    command: ["node", "app.js"]  # Ensures that the backend uses node app.js

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    networks:
      - worksync-network
    command: ["npm", "start"]  # Ensures that frontend runs with npm start

networks:
  worksync-network:
    driver: bridge
